name: star_sandwich
description: Mobile application that determines the nearest star at the observer's zenith and nadir.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.1.5+8

# Built with flutter 3.38.6 â€¢ channel stable

environment:
  sdk: '>=3.10.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.6.0
  geolocator: ^14.0.2
  flutter_svg: ^2.2.3
  shared_preferences: ^2.5.4
  package_info_plus: ^9.0.0
  auto_size_text: ^3.0.0
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.3.2
  flutter_launcher_icons: ^0.13.1

# flutter pub run flutter_launcher_icons:main
flutter_icons:
  ios: true
  android: false
  remove_alpha_ios: true
  image_path: "assets/launcher/star_sandwich_icon.png"

# flutter pub run flutter_native_splash:create
flutter_native_splash:
  color: "#292929"

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/svgs/
    - assets/launcher/